server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: ranbow-restaurant-order-app
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://192.168.0.114:5432/ranbow_restaurant}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password123}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: RanbowRestaurantPool

  # Redis 配置
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      password: ${SPRING_REDIS_PASSWORD:password123}
      timeout: 2000ms
      connect-timeout: 2000ms
      jedis:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 5
          max-wait: 2000ms

  # Session 配置
  session:
    store-type: redis
    redis:
      namespace: ranbow:session

  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# JWT 配置
jwt:
  secret: ${JWT_SECRET:ranbow-restaurant-jwt-secret-key-change-in-production}
  expiration: ${JWT_EXPIRATION:86400000}

logging:
  level:
    com.ranbow.restaurant: DEBUG
    org.springframework.jdbc: DEBUG
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/restaurant-app.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always