server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: ranbow-restaurant-order-app
  
  datasource:
    url: jdbc:postgresql://192.168.0.114:5432/ranbow_restaurant
    username: postgres
    password: Patycri3r
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: RanbowRestaurantPool

  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

logging:
  level:
    com.ranbow.restaurant: DEBUG
    org.springframework.jdbc: DEBUG
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/restaurant-app.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always